services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: catering-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/chaicharoen
      - JWT_SECRET=your_jwt_secret_here
      - PORT=8080
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: catering-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
